allowBreak: false

# Do not set me manually! Use /pl setspawn to set this.
spawn_coordinates: ""
voidtp_y: ""

antidamage: true

messages:
  playerJoinMessage: "<green>+ <#e0f2fe>{{PLAYER}}"
  playerLeaveMessage: "<red>- <#e0f2fe>{{PLAYER}}"